# -*- coding: utf-8 -*-
"""Basic Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qcp2Nyf0fIRpVowDCadpBskVdyOUHWO_

Menghitung jumlah bilangan genap pada range 1 - 100 yang dikuadratkan serta menghitung nilai rata ratanya
"""

even=[x for x in range(1,100) if x %2==0]
squares=[x**2 for x in even]
total=sum(squares)
ratarata=total/len(squares)
print(total)
print(ratarata)

"""Mengecek apakah bilangan yang diinput integer atau float"""

x = float(input('Masukkan nilai x = '))
if x == int(x) : 
  print('x adalah Integer')
else : 
  print('x adalah float')

while True : 
  x = int(input('Masukkan inputan angka : '))

  if x < 100 :
    print('Small Value')
  elif 100 < x < 200 :
    print('Medium Value')
  else :
    print('Big Value')
    break

while True : 
  pw = input('Masukkan password anda : ')
  p1 = '1' in pw
  p2 = '$' in pw

  if len(pw) <5 :
    print('Password terlalu sedikit')
  elif p1 !=  True :
    print('Harus mengandung angka 1')
  elif p2 != True :
    print('Password harus mengandung $')
  else : 
    print('Password bisa digunakan')
    break

count=0
contoh_list=['acc', 'xyz', 'aba', '1221']
for i in range(len(contoh_list)):
  if(contoh_list[i][0] == contoh_list[i][-1]):
    count += 1
print('jumlah string yg sama=',count)

"""**Penjelasan Program Diatas**

Program diatas merupakan program perulangan for, yang mana berulang untuk membaca contoh_list sebagai list yang berisi beberapa elemen. Perulangan akan terjadi didalam range banyak elemen contoh_list. Kemudian terdapat struktur keputusan if else, yang mana pada pernyataan if, akan dijalankan perulangan dan di cek value pada contoh_list. Index 0 sampai ke i pada contoh_list akan dijalankan dengan mengecek apakah nilai valuenya sama jika elemen dari list dibaca dari awal dan dibaca dari akhir elemen. Jika valuenya sama, maka akan ditambah nilai count yang mana count berfungsi sebagai variabel yang mewakili true ketika value dibaca dari awal sama dengan dibaca dari akhir
"""

while True:
    kata=input("Masukkan kata/angka yang akan dicek palidrom atau tidak ")
    bkata= kata.split()
    if kata == kata[::-1]:
        print("kata/angka merupakan palidrom dengan jumlah string sebanyak ", len(bkata))
        break
    else:
        print("Kata/angka yang anda input bukan palidrom")

def hitung(s):
    d={'upper':0,'lower':0}
    for x in s:
        if x.isupper():
            d['upper']+=1
        elif x.islower():
            d['lower']+=1  
        else :
            print('string merupakan angka')
            return
    print('string kalimat:', s)
    print('jumlah huruf kapital:',d['upper'])
    print('jumlah huruf kecil',d['lower'])
             
hitung('232323')
print('\n')
hitung('aSdwa')

#Angka Ganjil 
list2=[121,214,12,123,12314,122,34]
print('Menampilkan angka ganjil dari list berikut:',list2)
for i in list1:
    if i%2==1 :
        print(i,end=" ")

#Angka Genap
list1=[121,214,12,123,12314,122,34]
print('Menampilkan angka genap dari list berikut:', list1)
for i in list1:
    if i%2==0 :
        print(i,end=" ")

#Program Kalkulator Sederhana
print('Masukkan Pilihan operasi yang ingin digunakan : \n')
print('1.Penjumlahan \n2.Pengurangan \n3.Perkalian \n4.Pembagian\n')
x = int(input('Masukkan pilihan : '))
a = float(input('Masukkan angka pertama : '))
b = float(input('Masukkan angka kedua : '))
if x == 1 :
  print(a,"+",b,"=",a+b)
elif x == 2 :
  print(a,'-',b'=',a-b)
elif x == 3 :
  print(a,'*',b,'=',a*b)
elif x == 4 :
  if b != 0 :
    print(a,'/',b,'=',a/b)
  else :
    print('Tidak bisa melakukan pembagian dengan angka nol')
else :
  print('Input yang anda masukkan salah')

#meminta input celcius yang ingin di konversi
celcius = float(input('Masukkan Suhu(celcius) yang ingin dikonversi = '))

#konversi suhu
F = (9/5)*celcius + 32
R = (4/5)*celcius
K = celcius + 273.15
Rankine = (celcius + 273.15) * (9/5)
print(f'{celcius}C = {F} F')
print(f'{celcius}C = {R} R')
print(f'{celcius}C = {K} K')
print(f'{celcius}C = {Rankine} Ra')